#!/bin/bash

#┌───────────────────────────────────────────────┐
#│ Провреряем существует-ли каталог node_modules │
#└───────────────────────────────────────────────┘
if [ ! -e "./node_modules" ]; then
    clear
    npm cache clean --force
    npm install --no-package-lock
fi

#┌──────────────────────┐
#│ Запускаем приложение │
#└──────────────────────┘
clear
/usr/bin/node ./app.js
